### PR TITLE
Add homebrew formulae

### PR DESCRIPTION
**Pull request by abhi3700**
## Description
This PR is to add Homebrew formulae for [pulsar](https://github.com/subspace/pulsar/), facilitating easy installation on macOS.

As the installation can be done based on the formulae `pulsar.rb` code on `main` branch, so I tested via pushing the PR's code to another dummy [repo](https://github.com/abhi3700/homebrew-pulsar2).

Tested OK ✅

With this PR, this [issue](https://github.com/subspace/pulsar/issues/270) can be resolved.

### CODE REVIEW

**Review by nazar-pc — COMMENTED** [review]
I'm a bit confused, do you expect this to still be a separate repo? I expected this to be submitted to the Pulsar itself.

**Comment by abhi3700** [comment]
@nazar-pc 
> I'm a bit confused, do you expect this to still be a separate repo? I expected this to be submitted to the Pulsar itself.

The intent is to make the `pulsar.rb` file hosted somewhere (as repo) & keep user away from downloading the entire pulsar repo so as to make the process look simple.

> Not saying we can't do with `pulsar` repo though.

Let me know your thoughts.

**Comment by nazar-pc** [comment]
I see, what about an automation that would push a commit to a gh-pages branch after new macOS build of Pulsar is out? That way we don't need to update it manually ever again and GitHub Pages will take care of hosting it and avoid downloading the whole repo (that is assuming "static website" is a supported way in homebrew).

**Comment by abhi3700** [comment]
> I see, what about an automation that would push a commit to a gh-pages branch after new macOS build of Pulsar is out? That way we don't need to update it manually ever again and GitHub Pages will take care of hosting it and avoid downloading the whole repo (that is assuming "static website" is a supported way in homebrew).

I was thinking for a while & also confirmed with @DaMandal0rian:

- Homebrew doesn't support static gh-page.
- Homebrew should be hosted on a separate repo as done here.

Putting here @DaMandal0rian's plan:

> "Basically, I would trigger a job when new pulsar release is out, it dispatches the tag and sha to the homebrew repo, homebrew repo has an action to build the new formulae, and then a PR is opened by that action, then enable auto merge on the action so PRs are merged automatically if requirement checks pass. Alternatively, there is an action that does this without needing to dispatch data and will shorten the process.
https://github.com/marketplace/actions/bump-homebrew-formula "

I will let @DaMandal0rian take over from here.

**Comment by nazar-pc** [comment]
> "Basically, I would trigger a job when new pulsar release is out, it dispatches the tag and sha to the homebrew repo, homebrew repo has an action to build the new formulae, and then a PR is opened by that action, then enable auto merge on the action so PRs are merged automatically if requirement checks pass. Alternatively, there is an action that does this without needing to dispatch data and will shorten the process.
    https://github.com/marketplace/actions/bump-homebrew-formula "

I like this plan!

**Comment by abhi3700** [comment]
@nazar-pc 
Can we merge this PR for the current release 0.7.4?

I will open an issue with @DaMandal0rian's plan, which can be submitted as another PR.

**Review by nazar-pc — APPROVED** [review]
Since we are keeping this repo, yes. Thanks for doing this!

**Comment by DaMandal0rian** [comment]
@abhi3700 I think you tagged the wrong person 😆

**Pull request merged**
